{"name": "test_01", "status": "failed", "statusDetails": {"message": "AssertionError: 1 != 2", "trace": "self = <test_pytest.test_assert.Test_demo testMethod=test_01>\n\n    def test_01(self):\n    \n>       self.assertEqual(1,2)\nE       AssertionError: 1 != 2\n\ntest_assert.py:10: AssertionError"}, "start": 1666798540027, "stop": 1666798540028, "uuid": "c351444c-bed4-4896-905b-487c627b1ec1", "historyId": "22e20720d9bcd312ca31382863204e1f", "testCaseId": "1e435a30656bcd48e53b49b53a43f996", "fullName": "test_assert.Test_demo#test_01", "labels": [{"name": "suite", "value": "test_assert"}, {"name": "subSuite", "value": "Test_demo"}, {"name": "host", "value": "LAPTOP-GID304T1"}, {"name": "thread", "value": "11764-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_assert"}]}